name: smt
channels:
  - https://conda.anaconda.org/gurobi
  - conda-forge
  - defaults
dependencies:
  - colorama=0.4
  - matplotlib=3.6
  - numpy=1.23
  - pandas=1.5
  - python=3.10
  - scipy=1.9
  - tqdm=4.64
  - pip:
    - multiprocess==0.70.14
    - scikit-learn==1.2.0